WTF_CSRF_ENABLED = True
SECRET_KEY = 'you-will-never-guess'
SERVER_NAME= 'test-app.com'
MYSQL_DATABASE_USER = 'root'
MYSQL_DATABASE_PASSWORD = '67435076'
MYSQL_DATABASE_DB= 'KTV'
MYSQL_DATABASE_HOST = 'localhost'
